name: Build LaTeX document
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Upload PDF to workflow tab
        uses: actions/upload-artifact@v2
        with:
          path: main.pdf

  build_latex_loi:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: loi.tex
      - name: Upload PDF to workflow tab
        uses: actions/upload-artifact@v2
        with:
          path: loi.pdf

  deploy_pdfs:
    runs-on: ubuntu-latest
    needs: [build_latex, build_latex_loi]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Add in timestamp
        run: |-
          sed -i "s/%%timestamp%%/$(TZ=':US/Eastern' date +'%Y-%m-%dT%H:%M:%S')/g" site/index.html
      - name: Download pdfs
        uses: actions/download-artifact@v2
        with:
          path: site
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: site # The folder the action should deploy.
