name: Build LaTeX document
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Upload PDF to workflow tab
        uses: actions/upload-artifact@v2
        with:
          path: main.pdf

  build_latex_loi:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: loi.tex
      - name: Upload PDF to workflow tab
        uses: actions/upload-artifact@v2
        with:
          path: loi.pdf
